apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm-ingress
  namespace: llm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - infomaniak.sofianedjerbi.com
      secretName: vllm-tls
  rules:
    - host: infomaniak.sofianedjerbi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vllm-proxy
                port:
                  number: 8080
