apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: proxy
  namespace: flux-system
spec:
  image: ghcr.io/sofianedjerbi/llama-domestique-proxy
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: proxy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: proxy
  filterTags:
    pattern: '^[a-f0-9]{40}$'
  policy:
    alphabetical:
      order: desc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: proxy
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: 'chore: update proxy image to {{range .Changed.Changes}}{{.NewValue}}{{end}}'
    push:
      branch: master
  update:
    path: ./clusters/llm/apps/llm
    strategy: Setters
