apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2//manifests/bases/image-reflector-controller?ref=v2.4.0
  - https://github.com/fluxcd/flux2//manifests/bases/image-automation-controller?ref=v2.4.0
  - image-automation.yaml
